version: 2.1
orbs:
  docker: circleci/docker@2.1.1
workflows:
  deploy:
    jobs:
      - dockerhub/publish:
          image: toska/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          extra_build_args: '--build-arg BASE_PATH=/stats/'
          filters:
            branches:
              only: master
